export const environment = {
  production: true,
  platformProviderApiBaseUrl: 'https://coldtrace-json-server.onrender.com',
  platformProviderUsersEndpointPath: '/users',
  platformProviderOrganizationsEndpointPath: '/organizations',
  platformProviderRolesEndpointPath: '/roles',
  platformProviderAssetsEndpointPath: '/assets',
  platformProviderIoTDevicesEndpointPath: '/iot-devices',
  platformProviderGatewaysEndpointPath: '/gateways',
  platformProviderAssetSettingsEndpointPath: '/asset-settings',
  platformProviderMaintenanceSchedulesEndpointPath: '/maintenance-schedules',
  platformProviderTechnicalServiceRequestsEndpointPath: '/technical-service-requests',
  platformProviderSensorReadingsEndpointPath: '/sensor-readings',
  platformProviderReportsEndpointPath: '/reports',
  platformProviderIncidentsEndpointPath: '/incidents',
  platformProviderSignUpEndpointPath: '/authentication/sign-up',
  platformProviderSignInEndpointPath: '/authentication/sign-in',
  platformProviderPasswordResetEndpointPath: '/password-reset-requests',
};
